name: Cpplint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Lint with cpplint
      run: |
        python -m pip install --upgrade cpplint
        python -m cpplint --recursive src tests/src
